README.md

Fix a typo, and add a WIP label to api link.

Update links in readme to WIP

---

README.md

license title is broken by previous commit

Fix wrong license title

---

CONTRIBUTING.md
OWNERS
README.md
RELEASE.md

Refactored to follow new repo template
Signed-off-by: Harry Zhang <harryz@hyper.sh>

Refactor to new repo template

---

.travis.yml
hack/boilerplate/boilerplate.Dockerfile.txt
hack/boilerplate/boilerplate.Makefile.txt
hack/boilerplate/boilerplate.go.txt
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/boilerplate/boilerplate.sh.txt
hack/test-go.sh
hack/update-gofmt.sh
hack/verify-all.sh
hack/verify-boilerplate.sh
hack/verify-govet.sh
pkg/manager/manager_test.go

This PR enables CI for frakti and 
- add hack/verify-govet.sh
- add hack/test-go.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/frakti/10)

Fix travis CI

---

pkg/hyper/helper.go
pkg/hyper/hyper.go

A part of #8 
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/11)

add delete pod

---

pkg/hyper/client.go
pkg/hyper/hyper.go

---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/12)

add version

---

pkg/hyper/client.go
pkg/hyper/helper.go
pkg/hyper/hyper.go
pkg/hyper/images.go

This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/14)

Add images api implementation

---

pkg/hyper/client.go
pkg/hyper/hyper.go

---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/13)

add stop pod

---

pkg/hyper/client.go
pkg/hyper/helper.go
pkg/hyper/hyper.go

A part of #8 
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/16)

Add PodSandboxStatus api implementation

---

pkg/hyper/client.go
pkg/hyper/helper.go
pkg/hyper/hyper.go

A part of #8 
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/20)

add list pod

---

pkg/hyper/client.go
pkg/hyper/helper.go
pkg/hyper/hyper.go

A part of #8 
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/21)

add container status

---

pkg/hyper/hyper.go

Signed-off-by: heartlock <21521209@zju.edu.cn>
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/24)

modify parameter of parseSandboxName()

---

pkg/hyper/client.go
pkg/hyper/hyper.go

---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/22)

add stop container

---

test/e2e/framework/util.go
test/e2e/pods.go

Signed-off-by: heartlock <21521209@zju.edu.cn>
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/25)

add podsandbox test case

---

pkg/hyper/client.go
pkg/hyper/hyper.go

---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/27)

add list containers

---

pkg/hyper/client.go
pkg/hyper/helper.go
pkg/hyper/images.go
test/e2e/framework/util.go
test/e2e/images.go

1. ImageList will return digest only image.
2. make image pulling timeout related with pulling progress, if it stuck(without progress) over 1 minute, context will be cancelled.
3. add e2e image test cases
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/26)

e2e image test

---

README.md

This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/28)

Add start kubernetes with frakti to readme

---

README.md

This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/30)

Add Go Report

---

pkg/hyper/images.go

This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/36)

Returns nil instead of error when image not found

---

pkg/runtime/runtime.go

Fix pkg alias to align with golang convention https://blog.golang.org/package-names
cc/ @resouer
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/37)

Fix pkg alias to align with golang convention

---

pkg/hyper/helper.go

Should use pointer in `json.Unmarshal`.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/38)

Fix json unmarshal in getAnnotationsFromLabels

---

pkg/hyper/client.go
pkg/hyper/container.go
pkg/hyper/helper.go
pkg/hyper/hyper.go

Signed-off-by: Xianglin Gao xlgao@zju.edu.cn
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/29)

Add create container

---

cmd/frakti/frakti.go
pkg/hyper/hyper.go
pkg/manager/manager.go

Start streaming server

---

hack/test-e2e.sh
test/e2e/cni.go
test/e2e/framework/util.go

step 1: configure cni in test-e2e.sh
step 2: add cni e2e test case

cni e2e test

---

pkg/hyper/images.go

Only filter images when ImageSpec.Image is not null.

Only filter images when ImageSpec.Image is not null

---

pkg/hyper/hyper.go
pkg/hyper/hyper_checkpoint.go

fix issue#86 create /var/lib/frakti/sandbox when init checkpoint

---

pkg/hyper/sandbox.go

fix #87 clean up checkpoint once sandbox non-exist

---

pkg/hyper/network.go

Maybe I forgot to refresh my last pr #85 , after I fixed this bug.
I'm so sorry for my negligence。
Signed-off-by: Yao Zengzeng <yaozengzeng@zju.edu.cn>

fix the bug that result is nil if no cni plugin provided

---

pkg/hyper/images.go

Avoid panic when image spec in filter is nil

---

hack/godep-save.sh

Add pre-restore mechanism in godep-save.sh, make sure we correctly update pkg like `k8s.io/client-go`. 
as @resouer mentioned in #93 .
This is enabled by adding `--pre-restore` flag, since we only need this when update these particular pkg. 

update godep-save.sh to enable restore some pkg before save

---

Godeps/Godeps.json
Makefile
cmd/frakti/frakti.go
contrib/systemd/frakti.service
pkg/util/logs/logs.go
vendor/k8s.io/apiserver/pkg/util/flag/configuration_map.go
vendor/k8s.io/apiserver/pkg/util/flag/flags.go
vendor/k8s.io/apiserver/pkg/util/flag/namedcertkey_flag.go
vendor/k8s.io/apiserver/pkg/util/flag/string_flag.go
vendor/k8s.io/apiserver/pkg/util/flag/tristate.go

Make frakti flags more comfortable by using`github.com/spf13/pflag`.
cc @resouer

Make frakti flags more comfortable

---

cmd/frakti/frakti.go
pkg/alternativeruntime/alternativeruntime.go

Support systemd cgroup driver

---

pkg/hyper/helper.go
pkg/hyper/sandbox.go

Fixes cgroups for burstable

---

test/e2e/streaming.go

[NEED TEST]Check stderr in streaming test since upstream fixed

---

CHANGELOG.md
docs/deploy.md

This PR fixes deploy guides with latest v0.2 release.

Fix deploy guides

---

cluster/allinone.sh
docs/deploy.md

Add all in one deployment of kubernetes with frakti

---

pkg/hyper/client.go

Signed-off-by: heartlock <21521209@zju.edu.cn>
@feiskyer Fix critest image test fail.
ref: #146

set force when remove image

---

.travis.yml
hack/install-docker.sh
hack/test-e2e.sh

Add critest

---

docs/deploy.md

There are some nits in deploy doc.

Fix bugs in deployment doc

---

hack/test-e2e.sh

CNI is moving its plugins to new repo, we should install via released
packages instead.

Install CNI plugin via released packages

---

cmd/frakti/frakti.go
docs/deploy.md
pkg/hyper/client.go
pkg/hyper/helper.go
pkg/hyper/hyper.go
pkg/hyper/sandbox.go

Automatically cherry-pick #152 and #153.

Automatically cherry-pick #152 and #153

---

pkg/hyper/ocicni/ocicni.go

This brings with it plugin chaining. ref: #122 
@feiskyer  Ready for review.
Signed-off-by: heartlock <21521209@zju.edu.cn>

Support cni plugin chaining

---

CHANGELOG.md
cmd/frakti/frakti.go

1. Updated the frakti version
2. Updated CHANGELOG

Release 0.3 of frakti

---

cmd/frakti/frakti.go
pkg/manager/manager.go
pkg/unikernel/container.go
pkg/unikernel/images.go
pkg/unikernel/sandbox.go
pkg/unikernel/streaming.go
pkg/unikernel/unikernelruntime.go
pkg/util/alternativeruntime/alternativeruntime.go

Add basic skeleton of unikernel runtime

---

pkg/hyper/ocicni/ocicni.go
pkg/hyper/sandbox.go

- Setup pod name correctly
- Fail out if CNI plugin fails
- Warn if getting checkpoint error

Fix CNI problems

---

pkg/hyper/sandbox.go

/cc @feiskyer 
Signed-off-by: Crazykev <crazykev@harmonycloud.cn>

rollback cni operation when RunPodSandbox failed

---

.travis.yml

Splitted Unit test and E2E test in seperate stages of Travis CI so that it's easy for user to debug what went wrong in the CI

Split Unit Test and E2E test in seperate Travis CI Stages

---

cluster/allinone.sh
docs/README.md
docs/networking.md
pkg/hyper/network.go
pkg/hyper/sandbox.go

This PR makes CNI supports old-versioned plugins. And also adds support for more network plugins, e.g. flannel and calico
Closes: #69 #150

Add support for more network plugins, e.g. flannel and calico

---

cluster/allinone.sh
docs/deploy.md

Add docs for approving kubelet's csr

---

cluster/allinone.sh
docs/deploy.md

increase memory limits for kube-dns

---

deployment/flexvolume/flexvolume-ds.yaml

The 1.0 tag on dockerhub is broken, change it to 0.1

Fix deploy nits

---

pkg/hyper/hyper_checkpoint.go
pkg/hyper/network.go
pkg/hyper/sandbox.go

Fixes #198.
- Clean up cni network on error
- Checkpoint ip addresses and host bridge
- Restore ip addresses before teardown cni

Improve cni network plugin workflow

---

README.md

Update the narrative about block device as volume.

Claim cinder volume is ready

---

deployment/flexvolume/cinder.conf.default

Fix tenant wrong word

---

Makefile

Fix nits in makefile

---

deployment/flexvolume/install.sh
pkg/flexvolume/cinder_util.go
pkg/util/knownflags/consts.go

Use cinder config path as const

Use default cinder config

---

README.md

Fix flannel typo in readme.md

---

pkg/hyper/fake_client_interface_test.go
pkg/hyper/streaming_test.go

Add unit test to streaming part.

Add streaming Test

---

Makefile

Usage:
```
export IMAGE_VERSION=your_version
make docker
```

Make image version configurable

---

pkg/hyper/network.go

This is because bridge-nf-call-iptables=1 is required for kubernetes. 
Fixes #239.

Bypass netfilter for the bridge.

---

cmd/frakti/frakti.go

Bump frakti version to 1.1

---

OWNERS

The assignee style owner file has been deprecated.

Use k8s style owners

---

docs/e2e-tests.md

grammar issues.

---

pkg/hyper/container.go

The previous code omit a error when hostpath is invalid.

Fix nil pointer when hostpath is invalid

---

docs/deploy.md

grammar issues

---

hack/lib/hyper.sh

Do not use subshell so that it is easier to see where ci fails.

fix ci build failures

---

pkg/hyper/sandbox.go

Fixes: #252 
Ref: https://github.com/hyperhq/hyperd/issues/671
cc @bergwolf

Fix ip with mask in pod status

---

pkg/hyper/client.go

`kuberuntime` relies on `docker/distribution` to parse image name to
full image path and pass it to `runtime.GetImageInfo()`:
e.g.
```
nginx -> docker.io/library/nginx
alexellis/echo  -> docker.io/alexellis/echo
```
But hyper only returns `alexellis/echo` in imageList, so we
need to fix the inconsistency here before doing filter. Otherwise it will report image not found.

Fix full docker image path inconsistency

---

hack/lib/hyper.sh

hyperstart kernel path has been changed

---

CHANGELOG.md
cmd/frakti/frakti.go
docs/deploy.md

Bump to frakti 1.1.1
Fixes: #258
Change log see: https://github.com/kubernetes/frakti/releases/tag/v1.1.1

Bump to frakti 1.1.1

---

docs/deploy.md
docs/networking.md

Claim to use flannel in deploy doc.

Claim using cni plugins for frakti

---

README.md

We need to update to use runV instead.

Update to use runv instead of hypercontainer

---

.travis.yml
docs/deploy.md
hack/install-docker.sh

Also, we may need to find reliable a way to get latest release version. See: #267

Use the latest frakti version in doc

---

cmd/frakti/frakti.go

Add a log for debugging streaming server address.

Add streaming server log for debug

---

pkg/util/alternativeruntime/alternativeruntime.go

fix a typo in alternativeruntime

fix a typo in alternativeruntime

---

pkg/hyper/network.go
pkg/hyper/sandbox.go

It is actually a required field now.
Fixes: #298

hyper: supply interface MTU

---

pkg/manager/manager.go

1.Describe what this PR did
fix pkg/manager golint warnings
2.Does this pull request fix one issue?
fixes part of #233 
3.Describe how you did it
refine codes
4.Describe how to verify it
➜  frakti git:(golint) golint pkg/manager/*    
➜  frakti git:(golint) 
5.Special notes for reviews
NONE

Fix: fix pkg/manager golint warnings

---

docs/deploy.md

Typo fix "Fannel"->"Flannel"

---

cluster/allinone.sh
cmd/frakti/frakti.go
docs/deploy.md

1.Describe what this PR did
update frakti version
2.Does this pull request fix one issue?
NONE
3.Describe how you did it
NONE
4.Describe how to verify it
NONE
5.Special notes for reviews
NONE

Fix: update frakti version

---

cmd/frakti/frakti.go
pkg/docker/privilegedruntime.go

Fixes kubernetes/kubernetes#55676

add a new flag pod-infra-container-image to override default sandbox image

---

OWNERS

Update OWNERS file to track latest commit history

Update OWNERS file to track latest commit history

---

hack/test-e2e.sh

Download from release directly.

Install right version of critool

---

pkg/flexvolume/gcepd/flexvolume.go

Correct the returned message

---

pkg/util/registrar/registrar.go

fix grammar msitake.

---

cmd/frakti/frakti.go

Update master with 1.10.0 release

Release 1.10.0

---

pkg/kata/proc/init.go
pkg/kata/proc/init_state.go
pkg/kata/process.go
pkg/kata/task.go

- Process() returns a process within the task for the provided id
- Metrics() returns the stats of a container
- CloseIO() closes the provided IO on the task
- Pause() pauses the container process
- Resume() unpauses the container process

Implement five tasks

---

docs/deploy.md

**1.Describe what this PR did**
Modify deploy.md
**2.Does this pull request fix one issue?**
None
**3.Describe how you did it**
None
**4.Describe how to verify it**
None
**5.Special notes for reviews**
None

Fix: deploy document

---

pkg/hyper/fake_client_interface_test.go

Fix some grammatical errors in message:
doesn't existed->doesn't exist

Fix some grammatical errors in message

---

CONTRIBUTING.md

We have moved this file to the k/community/contributors/guide folder.
/sig node
/assign @dchen1107 @derekwaynecarr 
/kind feature

Updated URL docs/guide/collab.md

---

docs/deploy.md

fix error link
