kubernetes/frakti

- README.md
Cause the code in k8s has changed, so update readme to fix the setps to start k8s with frakti.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/32)
> fix the setps to start k8s with frakti

- README.md
- pkg/hyper/helper.go
- pkg/hyper/hyper.go
CRI requires all timestamps in nanoseconds instead of seconds.
cc @resouer
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/33)
> Fix timestamp

- README.md
It is required after https://github.com/kubernetes/kubernetes/pull/36319.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/35)
> Enable experimental cri when starting kubernetes cluster

- pkg/hyper/container.go
- pkg/hyper/sandbox.go
Continue the loop on name parse error, assuming the errored container or sandbox is not managed by frakti.
Fixes #43.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/44)
> Continue the loop on name parse error

- pkg/hyper/client.go
resp is nil in grpc when there's error, this will cause nil pointer
cc @feiskyer
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/45)
> Return err only instead

- pkg/hyper/helper.go
Tested on latest k8s master, parameter like `512m` also works, it will be translated to `512M`.
Remove this outdated comment.
---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/frakti/48)
> Resource value has been fixed on upstream

- hack/boilerplate/boilerplate.py
- pkg/hyper/container.go
- pkg/hyper/types/types.pb.go
- test/e2e/containers.go
- test/e2e/images.go
- test/e2e/utils.go
1. Generate `volDetail` based on Mounts
2. Generate `UserVolumeReference` for container spec
3. Add e2e test for volume container
NOTE: This can not work unless workaround https://github.com/hyperhq/hyperd/issues/487 ( for example, remove volume Validate(), will also fix it soon)
> Enable container volume for frakti

- pkg/hyper/client.go
- pkg/hyper/hyper.go
- pkg/hyper/streaming.go
- pkg/manager/manager.go
- pkg/runtime/runtime.go
And also use k8s util ExitError as wrapper for exitCode.
This PR will help make support multiple runtime easier.
> Make Runtime api same as kubernetes/pkg/kubelet/api.RuntimeService

- pkg/hyper/client.go
Check the response of `hyper.PodRemove` and fix potential panic.
> Check the response of PodRemove

- pkg/hyper/client.go
This PR adds reconnection for hyperd API, or else frakti will lose connection when hyperd is restarted.
> Connect hyperd api with reconnection

- cmd/frakti/frakti.go
- pkg/util/flags/flags.go
Fixes #106 #97 
I copied `flags.go` out of vendor because we can only call `Hidden` before `Parse()`. So we have to modify `flags.go`.
> Fix log-dir and create path

- pkg/hyper/helper.go
Frakti will panic, when we annotation is not nil but labels are nil.
/cc @feiskyer 
> Avoid panic when labels are nil

- cluster/allinone.sh
- docs/deploy.md
Kubernetes unstable release breaks occasionally, this PR switches the deployment to stable version.
This PR also adds guide for setting subnet routes.
> Switch to kubernetes stable release

- cluster/allinone.sh
- docs/deploy.md
#137 switches to kubernetes stable release, but it doesn't fix all docs.
This PR fixes all places and also disables selinux.
> Fixes of switching to kubernetes stable release

- pkg/hyper/client.go
- pkg/hyper/streaming.go
close #134 
```
Version:  0.1.0
RuntimeName:  hyper
RuntimeVersion:  0.8.1
RuntimeApiVersion:  0.1.0
/ # ls
ls
bin   dev   etc   home  lib   proc  root  sys   tmp   usr   var
/ # exit
exit
```
/cc @feiskyer 
> Filter CodeExitError type error in Exec streaming API

- cmd/frakti/frakti.go
- pkg/hyper/helper.go
- pkg/hyper/hyper.go
- pkg/hyper/sandbox.go
In some cases, the default 64MB memory is not sufficient. This PR makes the default cpu and memory configurable.
It should help with rook.io (#151) with setting default memory to 512MB.
> Make default cpu and memory configurable

- hack/test-e2e.sh
CNI is moving its plugins to new repo, we should install via released
packages instead.
> Automatically cherry-pick #157

- README.md
We need to claim main differences with linux container runtimes, so developers will not get confused.
> Claim main differences with linux container runtimes

- cmd/frakti/frakti.go
Frakti v0.2 has been already released, but its version number is still old. This PR updates frakti version to 0.2.
Fixes #163.
> Fix version

- README.md
- hack/test-e2e.sh
- pkg/hyper/network.go
- pkg/hyper/ocicni/ocicni.go
- pkg/hyper/ocicni/types.go
- pkg/hyper/sandbox.go
What this PR does:
@feiskyer Thanks for your help! Ready for review.
Closes: #122
> Support portmapping

- pkg/hyper/sandbox.go
Only setup portmap when hostport is set, or else portmap plugin would report error.
With this PR, frakti should pass full node e2e conformance tests.
> Only setup portmap when hostport is set

- docs/deploy.md
Refer https://github.com/kubernetes/frakti/issues/173#issuecomment-309949774.
kubeadm v1.6 doesn't support deploying v1.7 clusters well, we should recommend stable version in our docs.
> Use kubernetes stable version in deploy guide

- cmd/frakti/frakti.go
- pkg/hyper/hyper.go
For #183. 
Bump frakti to version 1.0 and hyperd minversion to 0.8.1.
> Bump frakti to version 1.0

- pkg/hyper/ocicni/ocicni.go
- pkg/hyper/sandbox.go
Ignore the error that netns or bridge not exist, when kubelet stop pod multiple times.
Also move RemoveCheckpoint() after teardownRelayBridgeInHost()
in case it get error and return immediately without delete the relay bridge in host.
> ignore some error messages

- .gitignore
- Makefile
- deployment/flexvolume/Dockerfile
- deployment/flexvolume/cinder.conf.default
- deployment/flexvolume/flexvolume-configmap.yaml
- deployment/flexvolume/flexvolume-ds.yaml
- deployment/flexvolume/install.sh
- docs/deploy.md
Workflow (This will be added to Stackube after this PR is merged):
```shell
cat >flexvolume-configmap.yaml <<EOF
kind: ConfigMap
apiVersion: v1
metadata:
name: flexvolume-config
namespace: kube-system
data:
auth-url: "https://${SERVICE_HOST}/identity_admin/v2.0"
username: "admin"
password: "${ADMIN_PASSWORD}"
tenant-name: "admin"
region: "RegionOne"
EOF
kubectl create -f flexvolume-configmap.yaml
kubectl create -f ${FRAKTI_ROOT}/deployment/flexvolume/flexvolume-ds.yaml
```
The `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/cinder~flexvolume_driver/` should be created automatically with binary inside.
And `/etc/kubernetes/cinder` should have also be created with right content.
> Deploy flexvolume by DaemonSet

- docs/networking.md
- pkg/hyper/helper.go
- pkg/hyper/ocicni/ocicni.go
- pkg/hyper/sandbox.go
Fix #216.
To use weave network plugin, run
```sh
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```
> Support weave network plugin

- cmd/frakti/frakti.go
- pkg/unikernel/libvirt/libvirt_domain.go
- pkg/unikernel/libvirt/libvirt_domain_unsupported.go
- pkg/unikernel/libvirt/vmtools.go
- pkg/unikernel/metadata/container.go
- pkg/unikernel/metadata/sandbox.go
- pkg/unikernel/service/container.go
- pkg/unikernel/service/sandbox.go
- pkg/unikernel/service/unikernelruntime.go
1. enable basic unikernel log, we still need vm wrapper to reformat log from qemu.
2. enable vm ACPI, if not, it will hang at start time.
3. fix domain copy in ListDomains
4. enable basic libvirt bridge network for debug purpose.
/cc @feiskyer @resouer PTAL
> Enable unikernel runtime log

- README.md
The design proposals were organized according to SIGs in kubernetes/community#1010. This led to a broken link in the README.
> Fix link after design proposal move

- docs/deploy.md
The default resource limit of kube-dns is tend to be not enough even though we changed the default limit of hypervisor runtime.
And we really don't want to let kube-dns reserve a huge amount of memory resource of host.
So let's use Linux container runtime to handle it by annotating.
> Annotate kube-dns for good

- cluster/allinone.sh
Update frakti version.
Fix bug that if `/usr/bin/frakti` exists, bash will return with error. Now remove old frakti automatically and then download a new one.
> Update frakti version

- pkg/hyper/client.go
the current GetImageInfo list all images and filter them in frakti.
The `Filter` parameter in the request could be used for filter it
in the hyperd side, which could avoid transferring the full image 
list and dropping them then.
> GetImageInfo: use Filter to get image instead of a full list

- pkg/flexvolume/cinder/flexvolume.go
- pkg/flexvolume/gcepd/flexvolume.go
- pkg/flexvolume/metadata.go
- pkg/flexvolume/metadata_test.go
- pkg/hyper/container.go
- pkg/util/metadata/metadata.go
Share volume options json format between cinder and gcepd
flex volumes so that we use the json file contents rather
than hostpath to identify different flex volume types.
> Share flexvolume option file json format

- pkg/kata/proc/exec.go
- pkg/kata/proc/exec_state.go
- pkg/kata/proc/init.go
- pkg/kata/proc/init_state.go
- pkg/kata/proc/process.go
- pkg/kata/proc/types.go
- pkg/kata/process.go
- pkg/kata/runtime.go
- pkg/kata/server/container.go
- pkg/kata/server/sandbox.go
- pkg/kata/task.go
- vendor/github.com/kata-containers/agent/protocols/client/client.go
- run a new sandbox
- stop the sandbox
- create a new container
- start an existing container
- stop a running container
Here I modify unix addr which is parsed by grpc in vendor. Because containerd's grpc version is different from kata-runtime's grpc version. The version difference causes us to be unable to run the project.
> Implement runtime's fundamental functions
